#version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80" # On mappe le port 80 du conteneur au port 8080 de notre machine